### ISSUE TITLE
Handle off-pitch push against Fend breaking blitz

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/bbreplay#15]
`Replay_2020-08-16_10-12-51.db` has a blitz against someone with Fend who is in the end zone. It currently exceptions with:

```
Traceback (most recent call last):
  File "dump-data.py", line 74, in <module>
    for event in replay.events():
  File "/home/ibboard/Projects/bbreplay/bbreplay/replay.py", line 180, in events
    for event in self._process_turn(cmds, log_entries, board):
  File "/home/ibboard/Projects/bbreplay/bbreplay/replay.py", line 353, in _process_turn
    yield from self._process_block(targeting_player, target_by_idx, cmds,
  File "/home/ibboard/Projects/bbreplay/bbreplay/replay.py", line 642, in _process_block
    yield from self.__process_block_rolls(targeting_player, target_by_idx, cmd, cmds, moved,
  File "/home/ibboard/Projects/bbreplay/bbreplay/replay.py", line 766, in __process_block_rolls
    yield from self._process_movement(pushing_player, cmd, cmds,
  File "/home/ibboard/Projects/bbreplay/bbreplay/replay.py", line 1028, in _process_movement
    result = log_entry.result
AttributeError: 'SkillEntry' object has no attribute 'result'
```

This appears to be because the player continues moving after the blitz and the push off the pitch means that there isn't a `PushbackCommand`, which causes the code to jump to movement instead of fending.

**Comment by IBBoard** [comment]
Works fine after #11 was resolved
